version: '3.7'

services:
  logGenerator:
    container_name: logGen
    image: bash:latest
    command: bash -c "date=$(date); while (true) do echo '{\"message\":\"$date Cancelling transaction $rnd\"}' >> /output/file.log ; sleep 3; done"
    # Routes the `./output` directory from the host machine to the `/output` volume.
    volumes:
      - ./output:/output

  nodeapp:
    container_name: nodeapp
    image: nodeapp
    build:
      context: ./nodeapp
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "3000:3000"
    networks:
      - demoapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./api/data:/data/db
      - ./api/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - demoapp-network

  otelcol:
    container_name: otel-col
    image: otel/opentelemetry-collector-contrib:latest
    deploy:
      resources:
        limits:
          memory: 125M
    command: ["--config=/etc/otelcol-config.yml"]
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
      # - ./otelcollector/otelcol-config-filelog.yml:/etc/otelcol-config-filelog.yml
      - ./logs:/logs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "4317" # OTLP over gRPC receiver
      - "4318" # OTLP over http receiver
      - "8888"
      - "13133"
    environment:
      - ENVOY_PORT
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_HEC_URL=${SPLUNK_HEC_URL}
      - SPLUNK_MEMORY_TOTAL_MIB=${SPLUNK_MEMORY_TOTAL_MIB}
    networks:
      - demoapp-network

networks:
  demoapp-network:
    driver: bridge

